### PR TITLE
Simplify the plugin platform bundling process; Add exception for calls

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- The process for figuring out what binaries to exclude/include was a little complex, this simplifies it: specify which binaries you want to include
- If a plugin has a different set of binaries, add an exception for that repo name
- Assumes binaries are always in the same location: `server/dist`, and the binary names don't have any other prefix or postfix. These are reasonable assumptions, I would think.

#### Ticket Link
- none

### CODE REVIEW

**Comment by streamer45** [comment]
I am assuming we don't have access to the plugin's manifest right? Otherwise I guess it would probably be simpler and we wouldn't need the hard-code.

**Review by lieut-data — APPROVED** [review]
I think this approach makes sense, but should we loop in someone from the integrations team just to make sure we don't miss a particular plugin's edge case.

**Comment by cpoile** [comment]
@streamer45 I think we could parse the `plugin.json`, since we have the plugin bundle available. But I chatted with @lieut-data about it, and there are a couple benefits to having it hardcoded:
1. We're enforcing the rule that MM plugins should have the supported binaries
2. in the calls case, devs are building for local and then for distribution, and those could be different binaries, which means we'd have to have a "local" and a "ci" `plugin.json`, which would be added complexity

**Comment by streamer45** [comment]
> @streamer45 I think we could parse the `plugin.json`, since we have the plugin bundle available. But I chatted with @lieut-data about it, and there are a couple benefits to having it hardcoded:
> 
> 1. We're enforcing the rule that MM plugins should have the supported binaries
> 2. in the calls case, devs are building for local and then for distribution, and those could be different binaries, which means we'd have to have a "local" and a "ci" `plugin.json`, which would be added complexity

That makes sense. My only suggestion, which can be addressed as a later improvement, would be to possibly rely on config to achieve this "enforcing" behaviour rather than literally adding entries to a locally defined map, especially as I expect this to be a documented process that others could follow at some point.

**Review by streamer45 — APPROVED** [review]

**Review by levb — APPROVED** [review]

**Pull request merged**
