### PR TITLE
Ignore linux-arm64

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Like `darwin-arm64` before it, some plugins have begun building `linux-arm64`. Until we support this holistically, update the bundling heuristic for pre-packaged plugins to ignore linux-arm64 when present for now.

#### Ticket Link
None.

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
ok, until we dont release the plugins (at least the pre-packaged ones) we cannot complete the linux arm64 cycle
/cc @jasonblais

**Comment by cpanato** [comment]
@lieut-data there is a test failure can you take care that? after let me know then I can deploy it

**Comment by jasonblais** [comment]
cc @nab-77

**Comment by nab-77** [comment]
Is there fundamental difference in code used `linux-*` and `darwin-*`, is this simply not `arm64`? Build process needs the prefix?

Just check the changes, so we don't reference any other arch outside of arm64.

**Comment by lieut-data** [comment]
Oops, thanks @cpanato! Forgot to push the updated plugin.tar.gz used in the testing.

@nab-77, indeed `linux-*` and `darwin-*` are not compatible. But the root issue here is mostly that this code has not been updated to support more than one architecture per platform, so we're currently unable to cut plugin builds that include these binaries. We'll probably need to take a more holistic pass at this code to generate the necessary artifacts for use with the pre-packaged pipeline.

**Comment by cpanato** [comment]
deployed

**Pull request merged**
