### PR TITLE
Update marketplace success message based on mattermost-marketplace/pull/100

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Screenshot from 2020-08-28 12-27-39

I've also added a test.

#### Ticket Link
Follow up on https://github.com/mattermost/mattermost-marketplace/pull/100

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by jfrerich — CHANGES_REQUESTED** [review]
Nice enhancement.  what do you think about adding a description for the `--official` and `--community` flags.  They seem optional, but I feel we should explicitly mention when and why they should be used.  

Personally, I've never used those options

**Comment by hanzei** [comment]
Good point @jfrerich. These flag are not optional. They indicate if it's a plugin written and maintained by Mattermost or by the Open Source Community.

Do you have a proposal on where to add a description?

**Comment by hanzei** [comment]
@jfrerich I've updated the wording to make it more clear what the flags mean:
Screenshot from 2020-09-18 14-44-22

**Review by jfrerich — APPROVED** [review]
Thanks, @hanzei.  I think that clears up the flags confusion.  I was also going to suggest adding a note that one is required, but see the code checks and will notify the user if they don't include one flag.  https://github.com/mattermost/mattermost-marketplace/blob/master/cmd/generator/add.go#L51

**Pull request merged**
